Django_Exam/Django_Exam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Exam/app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', TodoHomeView.as_view(), name='home'),  
    path('message/', MessageView.as_view(), name='message'),
    path('error/', ErrorView.as_view(), name='error'),
    
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('profile/detail/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('verify/<int:pk>/<str:token>/', VerifyEmailView.as_view(), name='verify'),
    
    path('todo/create', TodoCreateView.as_view(), name='create_todo'),
    path('todo/detail/<int:pk>/', TodoDetailView.as_view(), name='todo_detail'),
    path('todo/update/<int:pk>/', TodoUpdateView.as_view(), name='todo_update'),
    path('todo/delete/<int:pk>/', TodoDeleteView.as_view(), name='todo_delete'),
]

Django_Exam/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core import validators

# Система управления задачами (Task Management System):
# Разработайте приложение, которое позволит пользователям создавать задачи,
# устанавливать приоритеты, добавлять комментарии и присваивать задачи другим 
# пользователям. Можно также добавить функционал уведомлений 
# о сроках выполнения задач



class Todo(models.Model):
    
    class TodoStatus(models.TextChoices):
        CREATED = "C", "created"
        IN_PROGRESS = "I", "in progress"
        DONE = "D", "done"
        
    class TodoPriority(models.TextChoices):
        LOW = "L", "low"
        MEDIUM = "M", "medium"
        HIGH = "H", "high"
    
    image = models.ImageField(upload_to="todo_images/", null=True, blank=True, verbose_name="Image", default="todo_images/default.jpg")
    title = models.CharField(max_length=100, verbose_name="Title", validators=[validators.MinLengthValidator(5, "Title must be greater than 5 charapters")])
    text = models.TextField(blank=True, verbose_name="Body", validators=[validators.MinLengthValidator(20, "Body must be greater than 20 charapters")])
    created = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Created")
    datecompleted = models.DateTimeField(null=True, blank=True, verbose_name="Completed")
    important = models.CharField(max_length=1, choices=TodoPriority.choices, default=TodoPriority.LOW, verbose_name="Priority")
    status = models.CharField(max_length=1, choices=TodoStatus.choices, default=TodoStatus.CREATED, verbose_name="Status")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Author", related_name="todos")
    perform = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Perform", related_name="perform", null=True, blank=True)
    
    

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "Task"
        verbose_name_plural = "Tasks"
        ordering = ["-important"]
        
        
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments", verbose_name="Author")
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE, related_name="comments", verbose_name="Task")
    text = models.TextField( verbose_name="Text")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    
    def __str__(self):
        return self.text
    
    class Meta:
        ordering = ['-created_date']
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

Django_Exam/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zilla+Slab:ital,wght@1,300&display=swap" rel="stylesheet">
    {% block title %}<title>My Exam Project</title>{% endblock %}
</head>

<body
    style=" background-image: url('https://catherineasquithgallery.com/uploads/posts/2021-02/1612728076_170-p-cherno-goluboi-fon-246.jpg');">
    {% include "navbar.html" %}
    <div class="base-container">
        {% block header %}{% endblock %}
        {% block content %}{% endblock %}
    </div>
    {% include "footer.html" %}

</body>

</html>

Django_Exam/templates/create_todo.html
{% extends "base.html" %}


{% block title %}<title>Create Todo</title>{% endblock %}
{% block header %}
<div class="copyright">
    <h1 class="base-header">Create Todo</h1>
</div>
{% endblock %}

{% block content %}
<div class="card zilla-slab-light-italic" style="min-height: 450px;">
    <form action="{% url 'create_todo' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btnCreateStyle zilla-slab-light-italic" style="margin-top: 10px; margin-left: 60px;" type="submit" value="Create">
    </form>
</div>
{% endblock %}

Django_Exam/templates/delete_todo.html
{% extends "base.html" %}

{% block title %}<title>Delete</title>{% endblock %}
{% block header %}
<div class="copyright">
    <h1 class="base-header" >Delete Todo</h1>
</div>
{% endblock %}

{% block content %}
<div class="profile" style=" min-height: 130px; color: rgb(51, 116, 172);" >
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete this todo"<span style="color: red;">{{todo.title}}</span>"?</p><br>
        <input class="btnCreateStyle" style="background-color: brown; color: rgb(196, 222, 245);" type="submit" value="Delete">
    </form>
</div>
{% endblock %}

Django_Exam/templates/error.html
{% extends "base.html" %}
{% load static %}


{% block title %}<title>No Access</title>{% endblock %}
{% block header %}
<div class="copyright">
    <h1 class="base-header">ДОСТУП ЗАПРЕЩЕН! Пожалуйста зарегистрируйтесь</h1>
</div>
{% endblock %}

{% block content %}
<div style="min-height: 570px; text-align: center">
    <p style="color: rgb(196, 222, 245);">
        Пожалуйста подождите, идёт перенаправление на страницу регистрации...</p>
        </div>
    <script>
        setTimeoutSignUp();
    </script>
{% endblock %}

Django_Exam/templates/footer.html
<footer id="footer" class="zilla-slab-light-italic">
    <section class="section1Footer">
        <ul>
            <p>Контактная информация:</p>
            <li class="fas fa-phone">  Телефон: +1234567890</li><br>
            <li class="fas fa-envelope">  Email: DjangoExam@example.com</li><br>
            <li class="fas fa-map-marker-alt">  Адрес: 123 Улица, Астана, Казахстан, 010000</li>
        </ul>
    </section>
    <section class="section2Footer">
        <ul class="social-icons">
            <p>Мы в социальных сетях:</p>
            <li class="fab fa-facebook">  <a  href="https://www.facebook.com/">Facebook</a></li>
            <li class="fab fa-twitter">  <a href="https://twitter.com/">Twitter</a></li>
            <li class="fab fa-instagram">  <a href="https://www.instagram.com/">Instagram</a></li>
            <li class="fab fa-telegram">  <a href="https://telegram.org/">Telegram</a></li>
        </ul>
    </section>
    <p class="aHover">©2024. Все права защищены. <br>
        Этот сайт создан в качестве экзамена к курсу "Python Django". <br>
        Автор: <a class="fab fa-github" href="https://github.com/DiAnonim"> DiAnonim</a></p>
</footer>

Django_Exam/templates/home.html
{% extends "base.html" %}

{% block title %}<title>Home</title>{% endblock %}
{% block header %}
<h1 class="base-header">Home</h1>
{% if request.user.is_authenticated %}
<h2 class="base-header">Welcome, {{request.user.username}}</h2>
{% else %}
<h2 class="base-header">Welcome, guest</h2>
{% endif %}
{% endblock %}

{% block content %}
<div class="zilla-slab-light-italic" style="color: rgb(196, 222, 245);">

    {% if request.user.is_authenticated %}
    <section class="tools ">
        <div class="aHover">
            <a href="{% url 'create_todo' %}"><img alt="">Create Todo</a>
        </div>
    </section>
    {% endif %}

    <h2 class="base-header">Todo List</h2>
    <section class="todo-list">
        {% for todo in todos %}
        <div class="todo-home">
            <h3 class="aHover"><a href=" {% url 'todo_detail' todo.id %} ">{{todo.title}}</a></h3>
            <p>Status: {{todo.get_status_display}}</p>
            <p>Created: {{todo.created}}</p>
            <p>Priority: {{todo.get_important_display}}</p>
            <p>Perform: {{todo.perform}}</p>
        </div>
        {% endfor %}
    </section>

    <section class="pagination">
        <div class="aHover pagination" >
            {% if page_obj.has_previous %}
            <a class="prev" href="?page={{ page_obj.previous_page_number }}">&lt;&lt;</a>
            {% endif %}
            Page <span class="current">{{ page_obj.number }}</span> of <span class="allPages">{{ page_obj.paginator.num_pages }}</span>
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">&gt;&gt;</a>
            {% endif %}
        </div>
    </section>
</div>
{% endblock %}

Django_Exam/templates/login.html
{% extends "base.html" %}

{% block title %}<title>Login</title>{% endblock %}
{% block header %}
<div class="copyright">
    <h1 class="base-header">Login</h1>
</div>
{% endblock %}

{% block content %}
<div class="card" style="min-height: 450px;">
    <form class="aHover" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p style="margin-top: 10px; margin-left: 37px;">Not registered? <a style="text-shadow: 0 0 10px rgb(0, 0, 0);"
                href="{% url 'signup' %}">Sign Up</a></p>
        <input style="margin-top: 10px; color: rgb(0, 0, 0); margin-left: 40px;" class="btnCreateStyle" type="submit"
            value="Login">
    </form>
</div>
{% endblock %}

Django_Exam/templates/message.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>Message</title>
{% endblock %}
{% block header %}
    <div class="copyright">
        <h1 class="base-header">Message</h1>
    </div>
{% endblock %}
{% block content %}
    <div style="min-height: 570px; text-align: center">
        <p style="color: rgb(196, 222, 245);">Пожалуйста подождите, идёт перенаправление...</p>

        {% for message in messages %}
            {% if message.tags == 'error' %}
                <p style="color:red">{{ message }}</p>
            {% elif message.tags == 'success' %}
                <p style="color:rgb(32, 225, 32)">{{ message }}</p>
            {% elif message.tags == 'warning' %}
                <p style="color:rgb(233, 166, 43)">{{ message }}</p>
            {% else %}
                <p>{{ message }}</p>
            {% endif %}
        {% endfor %}

        <script>
            setTimeoutHome();
        </script>
    </div>
{% endblock %}

Django_Exam/templates/navbar.html
{% load static %}

<nav class="darkNavbar zilla-slab-light-italic">
    <div id="logo">
        <img src="{% static 'images/logo3.png' %}" alt="">
    </div>
    <a href="{% url 'home' %}">Home</a>
    {% if not request.user.is_authenticated %}
    <a href="{% url 'signup' %}">Sign Up</a>
    <a href="{% url 'login' %}">Login</a>
    {% else %}

    <a class="fa fa-user" style="font-size: 15px;" href="{% url 'profile' user.id %}"> Profile</a>
    {% endif %}
</nav>

Django_Exam/templates/profile.html
{% extends "base.html" %}
{% load customtags %}


{% block title %}<title>Profile</title>{% endblock %}
{% block header %}
<div class="copyright">
    <h1 class="base-header">Your Profile</h1>
</div>
{% endblock %}

{% block content %}
<div class="profile zilla-slab-light-italic" style="min-height: 450px;">
    <h2>Username: <span>{{user.username}}</span></h2>
    <h2>First Name: <span>{{user.first_name | isHaveValue}}</span></h2>
    <h2>Last Name: <span>{{user.last_name | isHaveValue}}</span></h2>
    <h2>Email: <span>{{user.email | isHaveValue}}</span></h2>
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button  class="logout zilla-slab-light-italic" style="font-size: 22px; " type="submit"> Logout</button>
    </form>
</div>
{% endblock %}

Django_Exam/templates/signup.html
{% extends "base.html" %}
{% load static %}


{% block title %}<title>Sign Up</title>{% endblock %}
{% block header %}
<div class="copyright">
    <h1 class="base-header" >Sign Up</h1>
</div>
{% endblock %}

{% block content %}
<div class='card' style="min-height: 570px;">
    <form class="aHover" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p style="margin-top: 10px;" >Already have an account? <a style="text-shadow: 0 0 10px rgb(0, 0, 0);" href="{% url 'login' %}">Login</a></p>
        <input style="margin-top: 10px; color: rgb(0, 0, 96)" class="btnCreateStyle" type="submit" value="Sign Up">
        <a style="text-shadow: 0 0 10px rgb(0, 0, 0); margin-left: 20px;" href="{% url 'home' %}">Cancel</a>
    </form>
</div>
{% endblock %}

Django_Exam/templates/todo_detail.html
{% extends "base.html" %}


{% block title %}<title>Detail Todo</title>{% endblock %}
{% block header %}
<div class="copyright">
    <h1 class="base-header">Detail Todo</h1>
</div>
{% endblock %}

{% block content %}
<div class="profile aHover zilla-slab-light-italic" style=" min-height: 450px;">

    <div class="tools" style="width: 370px;">
        <a href="{% url 'home' %}">Back</a>
        <a href="{% url 'todo_update' todo.id %}">Update</a>
        <a href="{% url 'todo_delete' todo.id %}">Delete</a>
    </div>

    <br><img style="width: 300px; border-radius: 10px;" src="{{todo.image.url}}" alt="">
    <h2>Title: <span>{{todo.title}}</span></h2>
    <h2>Status: <span>{{todo.get_status_display}}</span></h2>
    <h2>Priority: <span>{{todo.get_important_display}}</span></h2>
    <h2>Description: <span>{{todo.text}}</span></h2>
    <h2>Created: <span>{{todo.created}}</span></h2>
    <h2>Deadline: <span>{{todo.datecompleted}}</span></h2><br>
    
    <h2>Author: <span>{{todo.author}}</span></h2>
    <h2>Perform: <span>{{todo.perform}}</span></h2><br>
    
</div>
{% endblock %}

Django_Exam/templates/update_todo.html
{% extends "base.html" %}


{% block title %}<title>Create Todo</title>{% endblock %}
{% block header %}
<div class="copyright">
    <h1 class="base-header">Create Todo</h1>
</div>
{% endblock %}

{% block content %}
<div class="card zilla-slab-light-italic" style="min-height: 450px;">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btnCreateStyle zilla-slab-light-italic" style="margin-top: 10px; margin-left: 60px;" type="submit" value="Update">
    </form>
</div>
{% endblock %}